apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.common.appName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    name: bss-init{{ .Values.instanceIdWithinNamespace }}
    release: {{ .Release.Name }}
    paw_instance_name: {{ .Values.paw_instance_name }}
  name: bss-init{{ .Values.instanceIdWithinNamespace }}
  namespace: {{ .Release.Namespace }}
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      annotations:
        hook.activate.cpd.ibm.com/command: '[]'
        hook.deactivate.cpd.ibm.com/command: '[]'
        cloudpakName: {{ .Values.cloudpakAnnotations.cloudpakName }}
        cloudpakId: {{ .Values.cloudpakAnnotations.cloudpakId }}
        productCloudpakRatio: {{ .Values.cloudpakAnnotations.productCloudpakRatio }}
        productName: {{ .Values.productName.PAWorkSpace }}
        productID:  {{ .Values.cloudpakAnnotations.productID }}
        productMetric: "VIRTUAL_PROCESSOR_CORE"
        productVersion: 3.5.2
        productChargedContainers: "All"
      labels:
        app.kubernetes.io/name: {{ .Values.common.appName }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        icpdsupport/addOnId: pa
        icpdsupport/app: "pa-workspace" 
        cloudpakInstanceId: "{{ .Values.zenCloudPakInstanceId }}"
        {{- include "planning-analytics.serviceid" . | indent 8 }}
        {{- if ( .Values.createdBy )  }}
        icpdsupport/createdBy: {{ .Values.createdBy | quote }}
        {{- end }} 
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        name: bss-init{{ .Values.instanceIdWithinNamespace }}
        release: {{ .Release.Name }}
        version: "1.0.242-ubi7"
        paw_instance_name: {{ .Values.paw_instance_name }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - {{ .Values.arch }}
      containers:
        - name: bss-init
          image: {{ .Values.docker_registry_prefix }}/pa-bss-init:1.0.242-ubi7
          env:
            - name: TM1Location
              value: "{{ .Values.common.tm1Location }}"
            - name: TM1ApplicationsLocation
              value: "{{ .Values.common.tm1ApplicationsLocation }}"
            - name: IBMCognosServlet
              value: "{{ .Values.common.ibmCognosServlet }}"
            - name: TM1APIPort
              value: "{{ .Values.common.tm1APIPort }}"
            - name: ENABLE_USER_IMPORT
              value: "{{ .Values.waProxy.enableUserImport }}"
            - name: ENABLE_PASTE_SPECIAL
              value: "{{ .Values.bssInit.enablePasteSpecial }}"
            - name: ENABLE_PAA
              value: "{{ .Values.bssInit.enablePAA }}"
            - name: ENABLE_EDIT_MDX_VIEW
              value: "{{ .Values.bssInit.enableEditMdxView }}"
            - name: ENABLE_INTENT_BAR
              value: "{{ .Values.bssInit.enableIntentBar }}"
            - name: WAProxyLocation
              value: "http://wa-proxy{{ .Values.instanceIdWithinNamespace }}.{{ .Release.Namespace }}.{{ .Values.common.internalDomainName }}:1331"
          resources:
            limits:
              cpu: "{{ .Values.bssInit.cpuLimit }}"
              memory: "{{ .Values.bssInit.memoryLimit }}"
            requests:
              cpu: "{{ .Values.bssInit.cpuRequestLimit }}"
              memory: "{{ .Values.bssInit.memoryRequestLimit }}"
          securityContext:
            runAsNonRoot: true
{{- if not (.Capabilities.APIVersions.Has "security.openshift.io/v1") }} 
            runAsUser: 2000
{{- end }} 
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - date
            initialDelaySeconds: 5
            periodSeconds: 60
          readinessProbe:
            exec:
              command:
                - date
            initialDelaySeconds: 0
            periodSeconds: 60
      hostNetwork: false
      hostIPC: false
      hostPID: false
      restartPolicy: OnFailure
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler

