apiVersion: v1
name: ibm-dsx-dev
description: IBM Data Science Experience (DSX) Developer Edition brings together best of breed open source tooling such as Jupyter, Zeppelin, RStudio, with Spark and Python,R and Scala runtimes to create a platform for Data Scientists to learn, create and collaborate.
version: 1.0.3
tillerVersion: ">=2.4.0"
keywords:
  - Data Science
  - Spark
  - R
  - Python
  - Scala
  - notebooks
home: http://datascience.ibm.com/desktop
icon: https://datascience.ibm.com/graphics/landing/logo.svg
maintainers:
 - name: IBM Analytics
