apiVersion: v1
kind: ServiceAccount
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.global.imagePullSecrets }}
  - name: {{ . }}
{{- end }}
{{- end }}
metadata:
  name: istio-multi
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "istio-remote.name" . }}
    chart: {{ template "istio-remote.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
