###############################################################################
# Licensed Materials - Property of IBM
# 5737-E67
# (C) Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
################################################################################

{{- include "sch.config.init" (list . "glusterfs.sch.chart.config.values") }}
{{- $heketisvcName :=  .sch.chart.components.heketisvc.name }}

kind: Service
apiVersion: v1
metadata:
  name: {{ include "sch.names.fullCompName" (list . $heketisvcName) }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "sch.metadata.labels.standard" (list . $heketisvcName) | indent 4 }}
    glusterfs: "heketi-service"
  annotations:
    description: Exposes Heketi Service
spec:
  type: ClusterIP
  selector:
    glusterfs: heketi-pod
  ports:
    - name: heketi
      port: 8080
      targetPort: 8080
