####################################################################
# Licensed Materials - Property of IBM                             #
# 5737-E67                                                         #
# (C) Copyright IBM Corporation 2016, 2018 All Rights Reserved     #
# US Government Users Restricted Rights - Use, duplication or      #
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.#
####################################################################

# Default values for f5-bigip-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

bigIp:
  __metadata:
    name: "bigIp"
    label: "F5 BIGIP Controller"
    description: "F5 BIGIP Controller related configuration"
  url:
    __metadata:
      name: "url"
      label: "URL"
      description: "BIG-IP admin IP address"
      type: "string"
      required: true
  partitionName:
    __metadata:
      name: "partitionName"
      label: "Partition Name"
      description: "BIG-IP partition in which to configure objects"
      type: "string"
      required: true
  username:
    __metadata:
      name: "username"
      label: "Username"
      description: "BIG-IP iControl REST username"
      type: "string"
      required: true
  password:
    __metadata:
      name: "password"
      label: "Password"
      description: "BIG-IP iControl REST password"
      type: "password"
      required: true
  poolMemberType:
    __metadata:
      name: "poolMemberType"
      label: "Pool Member Type"
      description: "The type of BIG-IP pool members you want to create"
      type: "string"
      default: "cluster"
      immutable: false
      required: true
      options:
      - label: "cluster"
        value: "cluster"
      - label: "nodeport"
        value: "nodeport"
  defaultIngressIp:
    __metadata:
      name: "defaultIngressIp"
      label: "Default Ingress IP"
      description: "IP Address for Ingresses annotated with virtual-server.f5.com/ip: 'controller-default'"
      type: "string"
  namespaces:
    __metadata:
      name: "namespaces"
      label: "Namespace(s)"
      description: "Kubernetes namespace(s) to watch"
      type: "string"
  nodeLabelSelector:
    __metadata:
      name: "nodeLabelSelector"
      label: "Node Label Selector"
      description: "Kubernetes node(s) with label to watch"
      type: "string"
  extraArgs:
    __metadata:
      name: "extraArgs"
      label: "Extra Arguments"
      description: "Other F5 BIG-IP K8S Controller Arguments"
      type: "string"

image:
  __metadata:
    label: "F5 BIGIP k8s Controller Image"
  repository:
    __metadata:
      name: "repository"
      label: "Repository"
      description: "Docker registry to pull k8s-bigip-ctlr image from."
      type: "string"
  tag:
    __metadata:
      name: "tag"
      label: "Tag"
      description: "k8s-bigip-ctlr image version"
      type: "string"
      required: true
  pullPolicy:
    __metadata:
      name: "pullPolicy"
      label: "Image Pull Policy"
      description: "Image pull policy for k8s-bigip-ctlr, the value can be 'Always', 'Never', or 'IfNotPresent'. Defaults to 'IfNotPresent'."
      type: "string"
      default: "IfNotPresent"
      immutable: false
      required: true
      options:
      - label: "IfNotPresent"
        value: "IfNotPresent"
      - label: "Always"
        value: "Always"
      - label: "Never"
        value: "Never"

resources:
  __metadata:
    label: "Resources"
  limits:
    __metadata:
      label: "Limits"
    cpu:
      __metadata:
        name: "limits.cpu"
        label: "Maximum CPU"
        description: "Describes the maximum amount of CPU allowed."
        type: "string"
        default: "200m"
        immutable: false
        required: false
    memory:
      __metadata:
        name: "limits.memory"
        label: "Maximum memory"
        description: "Describes the maximum amount of memory allowed."
        type: "string"
        default: "256Mi"
        immutable: false
        required: false
  requests:
    __metadata:
      label: "Requests"
    cpu:
      __metadata:
        name: "requests.cpu"
        label: "Minimum CPU"
        description: "Describes the minimum amount of CPU required. Corresponds to requests.cpu in Kubernetes."
        type: "string"
        default: "100m"
        immutable: false
        required: false
    memory:
      __metadata:
        name: "requests.memory"
        label: "Minimum memory"
        description: "Describes the minimum amount of memory required. Corresponds to requests.memory in Kubernetes."
        type: "string"
        default: "128Mi"
        immutable: false
        required: false
