####################################################################
# Licensed Materials - Property of IBM                             #
# 5737-E67                                                         #
# (C) Copyright IBM Corporation 2016, 2018 All Rights Reserved     #
# US Government Users Restricted Rights - Use, duplication or      #
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.#
####################################################################

# Default values for f5-bigip-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

bigIp:
  url: ""
  partitionName: ""
  username: ""
  password: ""
  poolMemberType: "cluster"
  defaultIngressIp: ""
  namespaces: []
  nodeLabelSelector: ""
  extraArgs: ""

image:
  repository: "f5networks/k8s-bigip-ctlr"
  tag: "1.6.0"
  pullPolicy: "IfNotPresent"

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
