####################################################################
# Licensed Materials - Property of IBM                             #
# 5737-E67                                                         #
# (C) Copyright IBM Corporation 2016, 2018 All Rights Reserved     #
# US Government Users Restricted Rights - Use, duplication or      #
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.#
####################################################################

{{- include "sch.config.init" (list . "f5bigipctlr.sch.chart.config.values") }}
{{- $crbName :=  .sch.chart.components.crb.name }}
{{- $crName :=  .sch.chart.components.cr.name }}
{{- $saName :=  .sch.chart.components.sa.name }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "sch.names.fullCompName" (list . $crbName) }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "sch.metadata.labels.standard" (list . $crbName) | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "sch.names.fullCompName" (list . $crName) }}
subjects:
- kind: ServiceAccount
  name: {{ include "sch.names.fullCompName" (list . $saName) }}
  namespace: {{ .Release.Namespace }}
