####################################################################
# Licensed Materials - Property of IBM                             #
# 5737-E67                                                         #
# (C) Copyright IBM Corporation 2016, 2018 All Rights Reserved     #
# US Government Users Restricted Rights - Use, duplication or      #
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.#
####################################################################

{{- include "sch.config.init" (list . "f5bigipctlr.sch.chart.config.values") }}
{{- $secretName :=  .sch.chart.components.secret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sch.names.fullCompName" (list . $secretName) }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "sch.metadata.labels.standard" (list . $secretName) | indent 4 }}
data:
  username: {{ required "Enter a valid username" .Values.bigIp.username | b64enc | quote }}
  password: {{ required "Enter a valid password" .Values.bigIp.password | b64enc | quote }}
