####################################################################
# Licensed Materials - Property of IBM                             #
# 5737-E67                                                         #
# (C) Copyright IBM Corporation 2016, 2018 All Rights Reserved     #
# US Government Users Restricted Rights - Use, duplication or      #
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.#
####################################################################

{{- include "sch.config.init" (list . "f5bigipctlr.sch.chart.config.values") }}
{{- $saName :=  .sch.chart.components.sa.name }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sch.names.fullCompName" (list . $saName) }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "sch.metadata.labels.standard" (list . $saName) | indent 4 }}
