kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: rstudio-server
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    run: rstudio-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      run: rstudio-server-deployment-pod
  template:
    metadata:
      labels:
        component: rstudio-server
        run: rstudio-server-deployment-pod
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: rstudio-server-container
          image: {{ .Values.rstudioServerContainer.image.repository }}:{{ .Values.rstudioServerContainer.image.tag }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy | quote }}
          command: ["/scripts/startup.sh"]
          resources:
{{ toYaml .Values.rstudioServerContainer.resources | indent 12 }}
          ports:
            - containerPort: 8787
              protocol: TCP
          volumeMounts:
             - mountPath: /user-home
               name: user-home-mount
      volumes:
        - name: "user-home-mount"
          persistentVolumeClaim:
          {{- if .Values.userHomePvc.persistence.existingClaimName }}
            claimName: {{ .Values.userHomePvc.persistence.existingClaimName }}
          {{- else }}
            claimName: {{ template "fullname" . }}-{{ .Values.userHomePvc.name }}
          {{- end }}
