{{ if (not .Values.userHomePvc.persistence.existingClaimName) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-{{ .Values.userHomePvc.name }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  {{- if .Values.persistence.useDynamicProvisioning }}
  storageClassName: {{ default nil .Values.userHomePvc.persistence.storageClassName | quote }}
  {{ else }}
  storageClassName: ""
  {{- end }}
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: {{ default "1Gi" .Values.userHomePvc.persistence.size | quote }}
  {{- if (not .Values.persistence.useDynamicProvisioning ) }}
  selector:
    matchLabels:
      assign-to: "user-home"
  {{- end }}
{{- end }}
