kind: Service
apiVersion: v1
metadata:
  name: zeppelin
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    run: zeppelin-server-svc
    component: zeppelin-server
spec:
  type: ClusterIP
  ports:
  - name: zeppelin-http-port
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    run: zeppelin-server-deployment-pod
    component: zeppelin-server
