apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibm-powervc-k8s-volume-default
  labels:
    app: ibm-powervc-k8s-volume-driver
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  {{ if .Values.driver.dfltStgClass }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{ end }}
{{ if .Values.driver.volumeType }}
parameters:
  type: "{{ .Values.driver.volumeType }}"
{{ end }}
provisioner: ibm/powervc-k8s-volume-provisioner
